project:
  type: website
  output-dir: docs
  title: "lumalazarini.github.io2"
  
website:
  title: "Luma Lazarini"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - lumalazarini.github.io2.qmd
      - experience.qmd
      - Research.qmd
      - courses.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true


editor: visual

