project:
  type: website
  output-dir: docs
  title: "lumalazarini.github.io2"
  
website:
  title: "Luma Lazarini"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lumalazarini.github.io2.qmd
        text: Interests
      - href: Research.qmd
        text: Research
      - href: courses.qmd
        text: Courses
      - href: resume.pdf
        text: Resume
        target: _blank
    page-footer: 
      background: dark
format:
  html:
    theme: 
      - style.scss
    css: styles.css
    fontcolor: $brown
    toc: true
    page-layout: full

editor: visual

