---
title: "Interests: Learn More About Me!"
format: html
toc: false
lightbox:
  match: auto
  effect: fade
  desc-position: right
  loop: false
  css-class: "my-css-class"
---

## {{< fa plane >}} Traveling

Studying abroad in Italy during Fall 2024 gave me the opportunity to fulfill a lifelong dream of exploring Europe. I visited unforgettable places like London, Paris, Nice, Croatia, Ibiza, and many cities across Italy. Below is a glimpse into four months of travel across Europe.

------------------------------------------------------------------------

## {{< fa music >}} Music

Music is one of my favorite ways to relax, have fun, and stay grounded. I have a wide-ranging taste that includes R&B, jazz, reggae, soft rock, pop, and hip hop. Check out the playlist below to see some of my favorite music.

<iframe style="border-radius:12px" src="https://open.spotify.com/playlist/35cJ2lkFfmFFXDldwfNQD3?si=CDr90D73SnGxpgB0PHQgCA" width="100%" height="352" frameBorder="0" allowfullscreen allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy">

</iframe>

------------------------------------------------------------------------

## {{< fa mitten >}} Crocheting

I started crocheting four years ago as a creative way to unwind and stay present and it's become one of my favorite pastimes! I enjoy crocheting at the beach, in the park, or during long car and plane rides. Some of the things I’ve made are shirts, bags, and beanies – check out some of my creations below.

------------------------------------------------------------------------

## {{< fa umbrella-beach >}} Beach

The beach is my happy place. It’s where I go to clear my mind and unwind from daily stress. In Isla Vista, you’ll often find me at Sands Beach, just a short walk from campus. When I’m home in San Diego, I love going to Windansea or Solana Beach, my favorites of all time.
